[phases.setup]
nixPkgs = ["nodejs-20_x", "npm"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci --include=optional",
  "npx puppeteer browsers install chrome"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
